Feature/reusable header component
peaksoft-school/bilingual-web pull request #6
Opened 2022-01-26 13:59 UTC by bolotbekMM

2022-01-26 14:50 UTC, zhumabek requested changes

2022-01-26 14:50 UTC, zhumabek commented on package.json
> +    "@emotion/styled": "^11.6.0",
emotion колдоносунарбы же styled-components? же экоону тен колдонуш керекби ?

2022-01-26 14:50 UTC, zhumabek commented on src/layout/header/Header.js
> +      <ThemeProvider theme={theme}>
бул эмне болгон themeProvider? в приложении должен главный themeProvider и он должен быть в самом корневом файле App.js

2022-01-26 14:50 UTC, zhumabek commented on src/layout/header/Header.js
> +                  <button className={classes.button} type="submit">
а эгер клиент эмес  роль админ болуп калсачы? вроде бы башка менюлар болот да ээ? 
анан кнопкаларга басканда эч нерсе болобойбу?

2022-01-26 15:06 UTC, bolotbekMM commented on package.json
> +    "@emotion/styled": "^11.6.0",
Kurmanjan тузгон reusable button колдонгом, ал button'дорду material UI менен тузгон экен ошого emotion коштум, мен  styled-component колдонгом

2022-01-26 15:09 UTC, bolotbekMM commented on src/layout/header/Header.js
> +      <ThemeProvider theme={theme}>
ок, App component'ке которуп койом. ThemeProvider button'дун стильин озгортуу учун керек экен.

2022-01-26 15:13 UTC, bolotbekMM commented on src/layout/header/Header.js
> +                  <button className={classes.button} type="submit">
ооба клиетке башка админге башка onClick bolot, башка меню болот. text button 'дор кок цветке алмашат башка анимация жок экен, onClick eventer эми кошулат

2022-01-28 16:40 UTC, zhumabek commented on src/layout/adminHeader/index.js
> +                  <StyledTextButton>tests</StyledTextButton>
кантип активный болот менюлар?

2022-02-03 12:46 UTC, merged